[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'junegunn/rainbow_parentheses.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'glepnir/zephyr-nvim'
hook_add = 'colorscheme zephyr'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
depends = 'nvim-web-devicons'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'git@github.com:YuuyWei/wiki.vim.git'
hook_add = '''
let g:wiki_root = '~/vimwiki'
let g:wiki_filetypes = ['md', 'wiki']
'''
