[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'glepnir/zephyr-nvim'
hook_add = 'colorscheme zephyr'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
depends = 'nvim-web-devicons'

[[plugins]]
repo = 'git@github.com:YuuyWei/wiki.vim.git'
hook_add = '''
let g:wiki_root = '~/vimwiki'
let g:wiki_filetypes = ['md']
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
'''

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope git_files<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>
lua <<EOF
require('telescope').setup {
  extensions = {
    fzy_native = {
      override_generic_sorter = false,
      override_file_sorter = true,
    }
  }
}
require('telescope').load_extension('fzy_native')
EOF
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzy-native.nvim'
on_source = 'telescope.nvim'
