[['plugins']]
repo = 'nvim-treesitter/nvim-treesitter'
on_event = 'BufRead'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
on_source = '''
let g:vim_markdown_autowrite = 1
let g:vim_markdown_new_list_item_indent = 1
let g:vim_markdown_math = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
