[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'glepnir/zephyr-nvim'
hook_add = 'colorscheme zephyr'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
depends = 'nvim-web-devicons'

[[plugins]]
repo = 'git@github.com:YuuyWei/wiki.vim.git'
hook_add = '''
let g:wiki_root = '~/vimwiki'
let g:wiki_filetypes = ['md']
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
'''

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>
lua <<EOF
require('telescope').setup {
  extensions = {
    fzy_native = {
      override_generic_sorter = false,
      override_file_sorter = true,
    }
  }
}
require('telescope').load_extension('fzy_native')
EOF
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzy-native.nvim'
on_source = 'telescope.nvim'


[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_add = '''
command! -bang -nargs=* -complete=file Make AsyncRun -program=make @ <args>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'YuuyWei/ywvim'
hook_add = '''
let g:ywvim_ims=[
            \['xh', '小鹤', 'xiaohe.ywvim'],
            \]
let g:ywvim_zhpunc = 1
let g:ywvim_listmax = 3
let g:ywvim_esc_autoff = 1
let g:ywvim_autoinput = 1
let g:ywvim_helpim_on = 1
let g:ywvim_matchexact = 0
let g:ywvim_chinesecode = 1
let g:ywvim_gb = 0
let g:ywvim_preconv = 'g2b'
let g:ywvim_conv = ''
let g:ywvim_lockb = 1
let g:ywvim_theme = 'dark'
let g:ywvim_intelligent_punc = 1
'''
